version: "3"

services:
  web:
    build: .
    depends_on:
      - db
    networks:
      - api
    command: ["./wait-for.sh", "db:5432", "--", "./run-migrations.sh"]
    volumes:
      - ./api:/code
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST}
      DJANGO_WEB_HOST: ${DJANGO_WEB_HOST}
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      APP_URL: ${APP_URL}


  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - api

networks:
  api:
    driver: bridge
