# Generated by Django 2.2.5 on 2019-09-30 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField()),
                ('team1', models.CharField(blank=True, max_length=128, null=True)),
                ('team2', models.CharField(blank=True, max_length=128, null=True)),
                ('toss_winner', models.CharField(blank=True, max_length=128, null=True)),
                ('toss_decision', models.CharField(blank=True, max_length=128, null=True)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
                ('dl_applied', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=128, null=True)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(blank=True, max_length=128, null=True)),
                ('venue', models.CharField(blank=True, max_length=128, null=True)),
                ('umpire1', models.CharField(blank=True, max_length=128, null=True)),
                ('umpire2', models.CharField(blank=True, max_length=128, null=True)),
                ('umpire3', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'unique_together': {('id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner', 'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs', 'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2', 'umpire3')},
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('batting_team', models.CharField(blank=True, max_length=128, null=True)),
                ('bowling_team', models.CharField(blank=True, max_length=128, null=True)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(blank=True, max_length=128, null=True)),
                ('non_striker', models.CharField(blank=True, max_length=128, null=True)),
                ('bowler', models.CharField(blank=True, max_length=128, null=True)),
                ('is_super_over', models.BooleanField(default=False)),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(blank=True, max_length=128, null=True)),
                ('dismissal_kind', models.CharField(blank=True, max_length=128, null=True)),
                ('fielder', models.CharField(blank=True, max_length=128, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ipl_stat.Match')),
            ],
            options={
                'unique_together': {('id', 'match', 'inning', 'batting_team', 'bowling_team', 'over', 'ball', 'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs', 'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs', 'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed', 'dismissal_kind', 'fielder')},
            },
        ),
    ]
